import type { CaptureMetadata, Case } from "../shared/index.js";

export interface ReportCapture {
  metadata: CaptureMetadata;
  screenshotDataUrl: string | null;
}

export interface ReportOptions {
  title: string;
  caseInfo?: Case;
  investigator: string;
  includeScreenshots: boolean;
  includeHashes: boolean;
  includeNotes: boolean;
}

export function generateReport(
  captures: ReportCapture[],
  options: ReportOptions,
): string {
  const sorted = [...captures].sort(
    (a, b) => a.metadata.timestamp.localeCompare(b.metadata.timestamp),
  );

  const now = new Date().toISOString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(options.title)}</title>
<style>
${REPORT_CSS}
</style>
</head>
<body>
<div class="report">

<header class="report-header">
  <h1>${esc(options.title)}</h1>
  <div class="report-meta">
    ${options.caseInfo ? `<div><strong>Case:</strong> ${esc(options.caseInfo.name)}</div>` : ""}
    ${options.caseInfo?.description ? `<div><strong>Description:</strong> ${esc(options.caseInfo.description)}</div>` : ""}
    ${options.investigator ? `<div><strong>Investigator:</strong> ${esc(options.investigator)}</div>` : ""}
    <div><strong>Generated:</strong> ${formatDateTime(now)}</div>
    <div><strong>Evidence Items:</strong> ${sorted.length}</div>
    <div><strong>Tool:</strong> Witness v0.1.0</div>
  </div>
</header>

<section class="toc">
  <h2>Table of Contents</h2>
  <ol>
    ${sorted.map((c, i) => `<li><a href="#evidence-${i + 1}">${esc(c.metadata.title || c.metadata.url)}</a> <span class="toc-date">${formatDateTime(c.metadata.timestamp)}</span></li>`).join("\n    ")}
  </ol>
</section>

${sorted.map((c, i) => renderEvidence(c, i + 1, options)).join("\n")}

<section class="chain-summary">
  <h2>Evidence Chain Summary</h2>
  <p>This report contains ${sorted.length} evidence item${sorted.length !== 1 ? "s" : ""} linked via SHA-256 hash chain. Each item's evidence hash is computed from its content hash, screenshot hash, metadata, and the previous item's hash, forming a tamper-evident chain.</p>
  <table>
    <thead><tr><th>#</th><th>Timestamp</th><th>URL</th><th>Evidence Hash</th></tr></thead>
    <tbody>
      ${sorted.map((c, i) => `<tr><td>${i + 1}</td><td>${formatDateTime(c.metadata.timestamp)}</td><td class="url-cell">${esc(c.metadata.url)}</td><td class="hash-cell">${c.metadata.evidenceHash.slice(0, 16)}...</td></tr>`).join("\n      ")}
    </tbody>
  </table>
</section>

<footer class="report-footer">
  <p>Generated by <strong>Witness</strong> &mdash; Open-source web evidence capture by <a href="https://happyhacking.space">Happy Hacking Space</a></p>
  <p>Report generated at ${formatDateTime(now)}</p>
</footer>

</div>
</body>
</html>`;
}

function renderEvidence(
  cap: ReportCapture,
  index: number,
  options: ReportOptions,
): string {
  const m = cap.metadata;
  const hits = m.selectorHits.length;

  return `
<section class="evidence-item" id="evidence-${index}">
  <h2><span class="evidence-num">#${index}</span> ${esc(m.title || "Untitled")}</h2>
  <div class="evidence-url"><a href="${esc(m.url)}">${esc(m.url)}</a></div>
  <div class="evidence-time">${formatDateTime(m.timestamp)}</div>

  ${options.includeScreenshots && cap.screenshotDataUrl ? `
  <div class="screenshot-wrap">
    <img src="${cap.screenshotDataUrl}" alt="Screenshot of ${esc(m.title)}" />
  </div>` : ""}

  <table class="evidence-fields">
    <tr><td>Format</td><td>${m.format.toUpperCase()}</td></tr>
    <tr><td>Size</td><td>${formatSize(m.contentSize)}</td></tr>
    <tr><td>Browser</td><td>${esc(m.browser.name)} ${esc(m.browser.version)}</td></tr>
    <tr><td>Platform</td><td>${esc(m.browser.platform)}</td></tr>
    ${options.includeHashes ? `
    <tr><td>Content Hash</td><td class="hash-cell">${m.contentHash}</td></tr>
    <tr><td>Screenshot Hash</td><td class="hash-cell">${m.screenshotHash ?? "N/A"}</td></tr>
    <tr><td>Evidence Hash</td><td class="hash-cell">${m.evidenceHash}</td></tr>
    <tr><td>Previous Hash</td><td class="hash-cell">${m.previousHash ?? "(genesis)"}</td></tr>
    ${m.rfc3161Token ? `<tr><td>RFC 3161 Timestamp</td><td>Present (trusted)</td></tr>` : ""}` : ""}
    ${hits > 0 ? `<tr><td>Selector Hits</td><td>${hits} match${hits !== 1 ? "es" : ""}</td></tr>` : ""}
  </table>

  ${m.tags.length > 0 ? `<div class="evidence-tags">${m.tags.map((t) => `<span class="tag">${esc(t)}</span>`).join(" ")}</div>` : ""}

  ${options.includeNotes && m.notes ? `
  <div class="evidence-notes">
    <strong>Notes:</strong>
    <p>${esc(m.notes)}</p>
  </div>` : ""}

  ${hits > 0 ? `
  <div class="evidence-hits">
    <strong>Selector Matches:</strong>
    <ul>
      ${m.selectorHits.map((h) => `<li><strong>${esc(h.selectorName)}:</strong> ${esc(h.matchedText)}</li>`).join("\n      ")}
    </ul>
  </div>` : ""}
</section>`;
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDateTime(ts: string): string {
  return new Date(ts).toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(0) + " KB";
  return (bytes / (1024 * 1024)).toFixed(1) + " MB";
}

const REPORT_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
    color: #1a1a2e;
    background: #fff;
    line-height: 1.6;
    font-size: 14px;
  }

  .report {
    max-width: 900px;
    margin: 0 auto;
    padding: 40px;
  }

  .report-header {
    border-bottom: 3px solid #1a1a2e;
    padding-bottom: 24px;
    margin-bottom: 32px;
  }

  .report-header h1 {
    font-size: 28px;
    font-weight: 700;
    margin-bottom: 16px;
    color: #1a1a2e;
  }

  .report-meta div {
    margin-bottom: 4px;
    color: #444;
  }

  .toc {
    margin-bottom: 40px;
    page-break-after: always;
  }

  .toc h2 {
    font-size: 20px;
    margin-bottom: 12px;
    color: #1a1a2e;
  }

  .toc ol {
    padding-left: 24px;
  }

  .toc li {
    margin-bottom: 6px;
    line-height: 1.4;
  }

  .toc a {
    color: #2563eb;
    text-decoration: none;
  }

  .toc a:hover { text-decoration: underline; }

  .toc-date {
    color: #888;
    font-size: 12px;
    margin-left: 8px;
  }

  .evidence-item {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 24px;
    margin-bottom: 32px;
    page-break-inside: avoid;
    background: #fafafa;
  }

  .evidence-item h2 {
    font-size: 18px;
    margin-bottom: 4px;
    color: #1a1a2e;
  }

  .evidence-num {
    color: #6366f1;
    font-weight: 700;
  }

  .evidence-url {
    margin-bottom: 2px;
    word-break: break-all;
  }

  .evidence-url a {
    color: #2563eb;
    font-size: 13px;
    text-decoration: none;
  }

  .evidence-time {
    color: #666;
    font-size: 13px;
    margin-bottom: 16px;
  }

  .screenshot-wrap {
    margin: 16px 0;
    border: 1px solid #ddd;
    border-radius: 4px;
    overflow: hidden;
    background: #000;
  }

  .screenshot-wrap img {
    width: 100%;
    display: block;
  }

  .evidence-fields {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 13px;
  }

  .evidence-fields td {
    padding: 6px 12px;
    border-bottom: 1px solid #eee;
  }

  .evidence-fields td:first-child {
    font-weight: 600;
    width: 160px;
    color: #555;
  }

  .hash-cell {
    font-family: "SF Mono", "Fira Code", monospace;
    font-size: 11px;
    word-break: break-all;
  }

  .url-cell {
    word-break: break-all;
    font-size: 12px;
  }

  .evidence-tags {
    margin: 12px 0;
  }

  .tag {
    display: inline-block;
    background: #e8e8ff;
    color: #4338ca;
    padding: 2px 10px;
    border-radius: 12px;
    font-size: 12px;
    margin-right: 6px;
  }

  .evidence-notes {
    margin: 12px 0;
    padding: 12px;
    background: #f0f0f0;
    border-radius: 6px;
  }

  .evidence-notes p {
    margin-top: 4px;
    white-space: pre-wrap;
  }

  .evidence-hits {
    margin: 12px 0;
  }

  .evidence-hits ul {
    padding-left: 20px;
    margin-top: 4px;
  }

  .evidence-hits li {
    font-size: 13px;
    margin-bottom: 2px;
  }

  .chain-summary {
    margin-top: 40px;
    padding-top: 24px;
    border-top: 2px solid #1a1a2e;
    page-break-before: always;
  }

  .chain-summary h2 {
    font-size: 20px;
    margin-bottom: 12px;
  }

  .chain-summary p {
    margin-bottom: 16px;
    color: #444;
  }

  .chain-summary table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }

  .chain-summary th, .chain-summary td {
    padding: 8px;
    border: 1px solid #ddd;
    text-align: left;
  }

  .chain-summary th {
    background: #f0f0f0;
    font-weight: 600;
  }

  .report-footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #ddd;
    text-align: center;
    color: #888;
    font-size: 12px;
  }

  .report-footer p { margin-bottom: 4px; }

  @media print {
    body { font-size: 12px; }
    .report { padding: 0; max-width: none; }
    .evidence-item { break-inside: avoid; }
    .toc { break-after: page; }
    .chain-summary { break-before: page; }
    a { color: inherit; text-decoration: none; }
    .screenshot-wrap img { max-height: 400px; object-fit: contain; }
  }
`;
